### PR TITLE
Add countries file and comment language file

### PR DESCRIPTION
**Pull request by gmartin7**

### CODE REVIEW

**Comment by gmartin7** [comment]
Hi Dan,
Let me know what you think.
I'm thinking of renaming the names of the json properties to match the actual data, but I haven't gotten the tests running yet. I'll need to change tests first, I'm sure, or the rename will cause some to fail.
Gordon

**Comment by gmartin7** [comment]
Running `npm test` gives:
`'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.`

**Comment by RaphaelDeLaGhetto** [comment]
Merged

**Comment by RaphaelDeLaGhetto** [comment]
Take a look in `package.json`. When you execute `npm test`, this is the command that is called: 

```
npm run build && NODE_ENV=test node_modules/.bin/jasmine
```

`NODE_ENV` is just an environment variable. What OS are you running? If it doesn't like environment variables, just remove it from the command defined in `package.json`.

**Comment by gmartin7** [comment]
I'm on Windows 10. I hadn't setup NODE_ENV as an environment variable, but
when I did, it didn't seem to help at all. :(

**Pull request closed without merging**
